### PR TITLE
Linear Search

### PR DESCRIPTION
**Pull request by karankeyash**
Added Linear Search in JavaScript

Ref : #1

### CODE REVIEW

**Review by Anuragkar234 — COMMENTED** [review]
Readme is already automated through workflow, so no need to change the readme.

**Comment by karankeyash** [comment]
I accidentally committed all the changes, but I did not change/modified README

**Comment by Anuragkar234** [comment]
> I accidentally committed all the changes, but I did not change/modified README

Is it possible for you to close this pull request and commit the LinearSearch.js file again though PR, it would be helpful.

**Comment by karankeyash** [comment]
Sure

**Pull request closed without merging**
